### ISSUE TITLE
Activity mode like in KDE

### ISSUE THREAD

**Issue by mercifulboss** [thrombe/hyprkool#16] opened 2024-10-10 05:37 UTC
KDE has workspaces (seperate desktops) but this is already supported.

It also has an "activity", which is essentially a whole new set of desktops/workspaces. This is useful because it allowws one to seperate work and gaming/miscellaneous things and have windows and programs open in seperate activities without interfering with one another.

Would it be possible to add? Clicking a button combo (like `Meta + Tab`) will switch activities and give access to a whole new set of empty workspaces to be able to seperate workflows in this way?

**Comment by thrombe** [comment] 2024-10-10 07:57
do you mean something like [this](https://github.com/thrombe/hyprkool/blob/master/README.md#L173)?

don't forget to add another entry in `actvities` in hyprkool.toml

**Comment by thrombe** [comment] 2024-10-11 09:22
yes. i know what kde activities are.
hyprkool activities are a group of workspaces. kinda like kde activities.
look at this video https://youtu.be/tim5r6Yo6TA
the buttons on the top bar show both hyprkool activities and workspaces on that activity

**Comment by thrombe** [comment] 2024-11-20 17:15
closing this as it's not clear what the issue is.

**Closed by thrombe** 2024-11-20 17:15 UTC
