### ISSUE TITLE
Slide Animation Direction

### ISSUE THREAD

**Issue by crackulator** [thrombe/hyprkool#8] opened 2024-05-08 21:39 UTC
Slide animation direction seems pseudo-random, whether changing desktops or activities (it appears repeatable, but doesn't make any sense that I can figure). I would expect that it would make some topological sense, though whether it will match the widget arrangement, of course would depend on the arrangement of the widgets.

**Comment by thrombe** [comment] 2024-05-08 22:01
animation direction is only supported if you are using the hyprkool plugin in addition to the cli. so make sure you have that installed and enabled.

assuming you have that installed, can you explain what weird behavior you are experiencing?

it is roughly supposed to be like this:
- using the `hyprkool move-<direction>` commands will have the animation be in the appropriate direction.
- any other way to switch workspaces / activities defaults to the fade animation. (it's hard coded mainly because there aren't many choices here)

**Comment by crackulator** [comment] 2024-05-09 19:22
Ok, I took a closer look, and my apologies, it's predictable, even sensible, though a little unexpected.

I have used your buttons in the same topographical arrangement, though I'm only using a single column of workspaces. So, activities go right to left, 123, and workspaces go down:
1
2
3

My keybindings to the move-up/downcommands behave as expected on the grid buttons, but the windows slide the opposite way. Like, when I move-down, the button shows it moving to the next desktop down, but the windows also slide down, which doesn't make sense to the arrangement of the desktops. If it's moving to a desktop down from the present, the windows would slide up. I presume I could address this in the eww button code by arranging the workspaces on the buttons to be the opposite order, but it seems a little strange to have them like 321 (or maybe not, depends on where you expect the origin to be).

Activities are less obvious, because there isn't any instinctive way they should be arranged. I have mine arranged in one row horizontally 1234. It is animating them vertically, which if you have to pick one makes as much sense as anything, but to really be topographical maybe the user needs to set that. How it appears on my system is that it slides up/down, and based on the slide direction, as if each next activity is above the other (ie if I go from activity 1 to activity 2, the windows slide down, implying that activity 2 is above activity 1. I find this unexpected, instinctively if there is an order I would expect the next activity to be below the present activity. And ideally, for my arrangement, I'd like to have the next activity to be to the right of the previous, so the windows should slide left when incrementing.

Which is, all this to say, I think it depends on one's expectations, and their button arrangements. It's quite likely that the only solution that will offer real coherence while letting them make their own buttons is to let the user set the topological directions in the configuration.

**Comment by thrombe** [comment] 2024-05-10 07:28
> How it appears on my system is that it slides up/- down

activities are hardcoded to have [fade](https://github.com/thrombe/hyprkool/blob/3fd44451006d2310b9a1e7b3d9c30f5b34a9d2e4/src/command.rs#L230) [animation](https://github.com/thrombe/hyprkool/blob/3fd44451006d2310b9a1e7b3d9c30f5b34a9d2e4/src/command.rs#L310). the CLI will set animation to Fade (if the plugin is active) and only then do the workspace switch (hypeland does not differentiate between hyprkool activities, everything is a workspace for hypaland). I don't see how this is happening.

does it show any errors when you execute `hyprkool next-activity` (also try `hyprkool toggle-overview`) in your terminal?

> I'd like to have the next activity to be to the right of the previous

it seems like you are trying to make a 2d grid out of these workspaces and activities. each activity is already a grid. asking out of curiosity, can you tell me why you are using activities in such a way?

> when I move-down, the button shows it moving to the next desktop down, but the windows also slide down

just like animations for `hyprkool next-activity`, animations for `hyprkool move-down` is also hardcoded to have the [correct animation](https://github.com/thrombe/hyprkool/blob/3fd44451006d2310b9a1e7b3d9c30f5b34a9d2e4/src/command.rs#L362). with `move-down`, windows  should move up. you can see it working correctly [here](https://www.reddit.com/r/unixporn/comments/1c9m7bu/hyprland_grid_workspace_plugin_with_overview/). if i can't reproduce this issue, i won't be able to help you. can you try to figure out what is wrong? try to read the readme of this repo. i have tried to include as much useful information as i could.

> depends on where you expect the origin to be

just to be clear, the workspaces are arranged like this
```
(x y)

(1 1) (2 1)
(1 2) (2 2)
(1 3) (2 3)
```
the y direction is flipped. maybe this should be mentioned in the readme.

**Comment by thrombe** [comment] 2024-05-10 07:45
> while letting them make their own buttons is to let the user set the topological directions in the configuration

to me, activities go in the z direction, it would be best to have popin / popout animations for these, but hyprland does not support these animations in v0.39 (latest version of hyprland supported by hyprkool as of now). it is possible to do it via a plugin, but it is not trivial to do. i will have to give it another shot.

hyprland does not support many animations for workspaces, so it didn't seem very practical to add config options for it. i'll do it if there's enough demand for it.

**Comment by crackulator** [comment] 2024-05-10 20:03
Let me take another look at my configuration. It sounds like what I am seeing is not what hyprkool does; it's probably hyprland doing the animation according to what it things the workspaces are, which wouldn't be sensible.

**Comment by crackulator** [comment] 2024-05-11 08:16
Well I think my conjecture above is correct, that I am seeing Hyprland's animations, not Hyprkool's. But I'm unable to get Hyprkool to do any animations. I rolled all the way back to your configurations, which I got from https://github.com/thrombe/dotfiles-promax/tree/372a47c0a7ed3c3280e110755803ee422c7c4977/configma/tools/home/.config (don't remember where I got that); I took eww and hypr from there. It's got your buttons and grids, and everything works like the demo except there are no transitions, just fast fades. I think that's why I started fiddling around with Hyprland's animation settings, and it looked like it kind of worked but the directions are all wrong.

So I guess the question is why I can't get Hyprkool to do any slide animations. I'm using the current Hyprkool from github, and Hyprland version 0.39.1.r4462.e57a2d7e-1. 

```
❯ hyprpm list
 → Repository hyprkool:
  │ Plugin hyprkool
  └─ enabled: true
```
Anything else I should look at?

**Comment by crackulator** [comment] 2024-05-12 04:03
BTW I was checking versions and I was on hyprkool 0.5.0, I noticed you have a 0.5.2, so I updated to that, no change.

**Comment by crackulator** [comment] 2024-05-12 04:19
As far as your question about my use of Activities being just like a column on a grid - well, yeah, it's definitely similar. Activities have names; I've modified my buttons to show the names. Even then, it wouldn't be quite the same as a grid with a column name, in the sense that I'm designing for both a 3-screen (all horizontally arranged) and single-screen scenarios. On 3 horizontal screens, having more virtual desktops in the horizontal dimension is unwieldy, and animation in that direction is kind of dizzying. On my 3-screen setup I would imagine 3 virtual desktops per activity, arranged vertically. That would seem very easy to keep track of.

But I want roughly the same interface for a single-screen setup, which would have a 2-dimensional grid per activity, probably 6 or 9 virtual desktops per activity.

In general I think your suggestion that workspaces should animate in the obvious directions, and then switches between desktops would be on a Z axis and therefore fade, is sensible. But I do like the sense of direction that animation gives me, and if I have buttons representing the activities, arranged either horizontally or vertically on my panel, it would be helpful to have animations respecting that direction (though I wouldn't find it necessary for them to show each screen on its way by).

I really appreciate this project because it promises to bring together 3 things that I can't get together anywhere else: Activities on Virtual Desktops, Automatic Tiling, and Animation. Plasma comes closest but their animation is screwy, tiling is weak, and it's real buggy. I've been working on something for Awesome but it'll never do animation.

**Comment by thrombe** [comment] 2024-05-13 01:55
> I noticed you have a 0.5.2, so I updated to that, no change.

i'd recommend always using hyprkool from the master branch. all development happens on the dev branch anyway.

also make sure to use hyprkool plugin and hyprkool cli+daemon from the same commit. and restart both the plugin and daemon after updating.

**Comment by thrombe** [comment] 2024-05-13 02:36
you have a pretty cool setup. I see now why you would want to have it that way.

**Comment by thrombe** [comment] 2024-05-13 02:39
there's one thing you can check. are you getting any errors printed by the daemon or the cli when you start the daemon or do hyprkool commands?

**Comment by crackulator** [comment] 2024-05-15 07:57
If I start the daemon from the command line, every time I switch desktops (using the eww buttons) I get messages like:

```
A unknown event was passed into Hyprland-rs
            PLEASE MAKE AN ISSUE!!
            The event was: workspacev2
A unknown event was passed into Hyprland-rs
            PLEASE MAKE AN ISSUE!!
            The event was: createworkspacev2
A unknown event was passed into Hyprland-rs
            PLEASE MAKE AN ISSUE!!
            The event was: destroyworkspacev2
```
Same if I do move-down from the cli.

Is pypr relevant? I saw that in your autostart.sh, but don't have it on my system.

**Comment by thrombe** [comment] 2024-05-15 15:38
you can ignore these. these will be fixed when hyprland-rs supports these events.

and no. pypr is not relevant here.

so no errors :(

i am confused why the animations won't work for you.

**Comment by crackulator** [comment] 2024-11-25 06:53
I figured it out... the plugin was enabled, but not running. I did not notice it was necessary to "reload" the plugins, I thought the report of it being "enabled" meant it was running.

**Comment by thrombe** [comment] 2024-11-25 08:15
that is good to know. i'll close this as resolved now.

**Closed by thrombe** 2024-11-25 08:15 UTC
