### ISSUE TITLE
overview not working on 0.41.1

### ISSUE THREAD

**Issue by HayyanAzzam** [thrombe/hyprkool#11] opened 2024-06-24 10:56 UTC
as the title says, when run manual error " hyprkool plugin must be running for this feature to work." is returned, and while on the way, if I open overview in a different activity, and move to another activity while it is open, and close it after that, when i go back to that activity overview will still be open there

**Comment by HayyanAzzam** [comment] 2024-06-24 11:08
+ going up and down goes left and right instead

**Comment by thrombe** [comment] 2024-06-24 18:59
> if I open overview in a different activity, and move to another activity while it is open, and close it after that, when i go back to that activity overview will still be open there

yes. that is the intended behavior.
for hyprkool, the overview is just a workspace.

**Comment by thrombe** [comment] 2024-06-24 19:01
> when run manual error " hyprkool plugin must be running for this feature to work."

can you check why the plugin is not running?
you can also try loading the plugin manually.

**Comment by thrombe** [comment] 2024-06-24 19:02
> * going up and down goes left and right instead

are you talking about the animations?
animations will not work if hyprkool-plugin is not running.

**Comment by thrombe** [comment] 2024-06-24 19:55
@HayyanAzzam hyprkool's plugin won't work for Hyprland 0.41.x right now. Hyprland is going through massive internal changes right now. so basically breaking the plugin every minor update. i was kinda waiting for those internal changes to get a bit more stable before working on hyprkool again.

i suggest using hyprland v0.40 if you really want hyprkool-plugin features.

**Comment by thrombe** [comment] 2024-06-27 20:34
i'll close this issue now. you faced this issue most likely cuz hyprkool-plugin 0.6 does not compile for Hyprland v0.41.x.

if the issue persists for hyprkool 0.7, please reopen the issue.

**Closed by thrombe** 2024-06-27 20:34 UTC
